### ISSUE TITLE
Test out ideas

### ISSUE THREAD

**Issue by Lauri-Nomme** [unapplicable/sort10M#1]
- [x] pin threads to distinct CPUs
** todo - osx support
- [x] use unrolled multiplier lookup table instead of strtol - slower
- [ ] test continuous instead of interleaved partitions 
** n parallel sequential reads starting at different offsets
- [x] progressively output sorted continuous prefix as soon as it's known
** needs coordination to propagate prefix tail between partition processors
** not worth it for test input, gap at 5
- [ ] build continuous chunks of output by extending them once elements are read, indexed by last element of chunk, sorted asc. in output phase, copy each to result file
- [x] instead of building an array of pointers, build an array of element content in partition processors, in output phase, scan for edges of continuous block in array and copy the block as a whole to output file - 470ms
- [ ] use SSE for atoi
